[package]
name = "wayland-sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
wayland-client = "0.31.5"
clap = { version = "4.5.16", features = ["derive"] }
nix = { version = "0.29.0", features = ["socket"] }